#!/usr/bin/env bash

current_git_directory=$(git rev-parse --git-dir 2>/dev/null)
msg="${current_git_directory}/kommit-message"

if [[ -f $msg ]]; then
    wrap_at=70
    if [[ $KOMMIT_WRAP_AT && $KOMMIT_WRAP_AT =~ ^-?[0-9]+$ ]]; then
        wrap_at=$KOMMIT_WRAP_AT
    fi
    out=$(fold -w $wrap_at -s "${msg}" | sed "s/^/    /")
    echo -e "\n\n$out\n\n" | cat - "${1}" > tmp_msg && 
        mv tmp_msg "${1}" &&
        rm -f "${msg}"
fi
